

// actions types
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_REQUEST_FAIL = 'PRODUCT_REQUEST_FAIL';
export const SINGLE_PRODUCT = 'SINGLE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

